### ISSUE TITLE
CLI Tool: URL unsafe IDs break

### ISSUE THREAD

**Issue by thejeshgn** [go-kivik/xkivik#88]
If the _id is say `2020-01-30T13:33:00.00+05:30|kl` breaks and says `Error: Not Found: missing`. I think it could be because its not URL encoded?

**Comment by flimzy** [comment]
It appears to be working for me locally. I expect the problem is actually your shell.  Are you quoting the id?

Example:

```shell
$ kivik get "foo/2020-01-30T13:33:00.00+05:30|kl"
{
        "_id": "2020-01-30T13:33:00.00 05:30|kl",
        "_rev": "1-967a00dff5e02add41819138abb3284d"
}
```

Without quotes, though:

```shell
$ kivik get foo/2020-01-30T13:33:00.00+05:30|kl
bash: kl: command not found
Error: Not Found: missing
```

If that doesn't solve your problem, can you provide a bit more information? Which operating system and shell are you using? And can you paste the exact command you executd, and the output it produced?

Thanks.

**Comment by thejeshgn** [comment]
Here are the three calls. First two fail with `Error: Not Found: missing` error.

```
thej@uma:~/code$ kivik get "covid19/2020-01-30T13:33:00.00+05:30|kl"
Error: Not Found: missing
thej@uma:~/code$ kivik get "covid19/2020-03-10T12:00:00.00+05:30|hr"
Error: Not Found: missing
thej@uma:~/code$ kivik get "covid19/add1e0bc7909fe6e00ddd78f8a05bbd2"
{
	"_id": "add1e0bc7909fe6e00ddd78f8a05bbd2",
	"_rev": "1-a2a874f5c1947ef5acea648baeb580cb",
	"category": "DarkGreen",
	"deaths": 1,
	"district": "Agra",
	"incident_date": "2020-03-28",
	"location": "Agra",
	"name_age": "Ranveer Singh (39)",
	"occupation": "migrant worker- restaurant",
	"reason": [
		"Exhaustion",
		"Migration"
	],
	"source": "m.timesofindia.com",
	"source_date": "2020-03-28",
	"source_link": "https://m.timesofindia.com/city/agra/food-delivery-boy-dies-after-walking-200-kms-to-agra-from-delhi/amp_articleshow/74864379.cms?__twitter_impression=true",
	"state": "UP",
	"type": "non_virus_deaths"
}
thej@uma:~/code$ 
```

**Comment by thejeshgn** [comment]
When I did
```
thej@uma:~/code$ kivik get doc "covid19/2020-01-30T13:33:00.00+05:30|kl" --verbose
> GET /covid19/2020-01-30T13:33:00.00+05:30%7Ckl HTTP/1.1
```

**Comment by thejeshgn** [comment]
I am happy to provide any other info.

Also thank you so much for Kivik. Its an amazing tool.

**Comment by flimzy** [comment]
Ah!  The problem is the handling of the `+` character. The --verbose output you included shows it's not being quoted properly. Thanks.  Let me see about a fix...

**Comment by flimzy** [comment]
I think I was wrong about that. `+` shouldn't need to be escaped in the path portion of a URL, only in the query portion.

Can you try this, and show me the output?

```shell
curl http://<host>/covid/2020-01-30T13:33:00.00+05:30|kl
```

And maybe also:

```shell
curl http://<host>/covid/_all_docs
```

**Comment by thejeshgn** [comment]
All docs is huge: You can see parts of them here 

`https://github.com/datameet/covid19/tree/master/data`



```
thej@uma:~/code$ curl "https://username:password@myserver.com/covid19/2020-01-30T13:33:00.00+05:30|kl"
{"error":"not_found","reason":"missing"}
```

👆 this is a surprise for me too. I had never used it with curl. I always used python couchdb or python cloudnant APIs.

**Comment by thejeshgn** [comment]
But this worked

`curl "https://username:password@example.com//covid19/2020-01-30T13%3A33%3A00.00%2B05%3A30|kl"`

**Comment by flimzy** [comment]
Fascinating. This apparently means that CouchDB itself has a bug... :open_mouth:  It requires query-parameter encoding for URL paths. I'll do a search on their bug list and maybe file one if it's not already there. But I'll need to allow working around it in Kivik, since a fix won't help with old versions.

**Comment by flimzy** [comment]
That is interesting.

Which version of the CouchDB server are you using?

**Comment by thejeshgn** [comment]
Oh wait. I have nginx infront of CouchDB. It may be because of that? I will
check. Sorry I didn't think of it before.

CouchdDB version 3.1.0

**Comment by flimzy** [comment]
I think I'm observing the same behavior on couch locally. So I do think it's a Couch problem.

**Comment by flimzy** [comment]
I was able to reproduce, and filed a bug upstream with CouchDB: https://github.com/apache/couchdb/issues/3565

The work-around should be pretty trivial in kivik, and should be safe enough even if/when they fix the upstream bug, so I'll work on that soon.

**Comment by thejeshgn** [comment]
Thank you.

**Comment by flimzy** [comment]
I have applied a fix to the `couchdb` driver here: https://github.com/go-kivik/couchdb/pull/278
And have updated the dependency on the CLI tool here: https://github.com/go-kivik/xkivik/pull/89

**Comment by flimzy** [comment]
https://github.com/go-kivik/xkivik/releases/tag/v4.0.0-alpha3 should contian the fixed code.

Thanks a lot for the bug report, and please let me know if anything else comes up!

**Comment by thejeshgn** [comment]
Tested. Works. Thank you.
